Sequelize relations
kpagacz/wiki-on-fire pull request #100
Opened 2021-11-19 22:42 UTC by mwiech99

Sequelize relations - done (Like_it, Comment, Recommend, Favourite)

2021-11-20 09:09 UTC, kpagacz commented on giddy-banana/seeders/20211115192909-demo-article.cjs
> +        title: "First articel",
```suggestion
        title: "First article",
```

2021-11-20 09:39 UTC, kpagacz commented on giddy-banana/models/Like_it.cjs
> +};
Do we need these functions when we have the associate methods?

2021-11-20 09:47 UTC, kpagacz commented on giddy-banana/migrations/20211118205548-create-comment.cjs
> +      date_added: {
Do we need data_added when there's createdAt?

2021-11-20 10:33 UTC, kpagacz commented on giddy-banana/models/index.cjs
> +db.Article = require("./article.cjs")(sequelize, Sequelize.DataTypes);
Shall we add comments to this as well?

2021-11-20 10:52 UTC, kpagacz commented on giddy-banana/models/index.cjs
> +db.Article = require("./article.cjs")(sequelize, Sequelize.DataTypes);
Or is it available implicitly? I assume it is.

2021-11-20 10:52 UTC, kpagacz commented on giddy-banana/seeders/20211115192909-demo-article.cjs
> +  }
Do we want to be able to undo this migration?

2021-11-20 10:53 UTC, kpagacz commented on giddy-banana/models/userModel.cjs
> +      models.User.belongsToMany(models.Article, { through: "Comment" });
What do you think about prepending the names with "User"? E.g.:
* UserLike
* UserRecommendation
* UserFavourite
* UserComment
or similar?

2021-11-20 10:54 UTC, kpagacz commented on giddy-banana/models/comment.cjs
> +};
What do you think about having a full fledged model for this available via db?

2021-11-20 11:17 UTC, kpagacz commented on giddy-banana/migrations/20211113210032-create-article.cjs
> +};
```suggestion
};

```

2021-11-20 11:17 UTC, kpagacz commented on giddy-banana/migrations/20211115184638-create-article.cjs
> +};
```suggestion
};

```

2021-11-20 11:18 UTC, kpagacz commented on giddy-banana/test.js
> +import db from "./models/index.cjs";
This is probably not needed in the final state of the PR

2021-11-20 11:30 UTC, kpagacz commented on giddy-banana/migrations/20211118205548-create-comment.cjs
> +        //primaryKey: true,
Comments probably not needed as well

2021-11-26 21:40 UTC, kpagacz commented on giddy-banana/models/article.cjs
> +       //models.Article.belongsToMany(models.User, { through: "Comment" });
Is there something wrong with this comment?

2021-11-26 21:41 UTC, kpagacz commented on giddy-banana/seeders/20211115192909-demo-article.cjs
> +  }
Can we add commands to undo this seed?

2021-11-26 21:42 UTC, kpagacz requested changes
This looks awesome!

Would you mind adding more seeds to the tables (so all the tables have at least one record)?

If it's too much for this, then please create a new issue and put it in priority. Thanks!

2021-12-02 13:05 UTC, mwiech99 commented
Of course, I'll add some seeds.

2021-12-02 19:24 UTC, mwiech99 commented
Relations and seeds done. Ready to review.

2021-12-05 01:19 UTC, kpagacz commented on giddy-banana/models/article.cjs
> +       //models.Article.belongsToMany(models.User, { through: "Comment" });
What about this comment?

2021-12-05 01:20 UTC, kpagacz commented on giddy-banana/models/comment.cjs
> +};
This double export is not going to work. You set the default export of this module twice.

2021-12-05 01:22 UTC, kpagacz commented on giddy-banana/models/index.cjs
> +Like_it(db);*/
Commented code?

2021-12-05 01:23 UTC, kpagacz commented on giddy-banana/models/comment.cjs
> +};
I think you probably wanted to remove the above lines.

2021-12-05 01:24 UTC, kpagacz requested changes
It's looking better and better.

I think this is ready to be merged, once you remove the commented out code.

2021-12-06 21:35 UTC, kpagacz approved these changes

2021-12-06 21:48 UTC, merged