Wof small error component
kpagacz/wiki-on-fire pull request #122
Opened 2021-12-04 02:07 UTC by robert10290

closes #54

2021-12-04 10:14 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +    position: absolute;
Why this is absolute?

2021-12-04 10:16 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +        position: absolute;
This probably should be position relative.

2021-12-04 10:16 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +                position: absolute;
This should not be absolute. Parent is already absolute.
Set width to 'fit-content'

2021-12-04 10:17 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +            align-content: left;
This is invalid property value (check in DevTools in Chrome)

2021-12-04 10:37 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +                margin-top: 0.75em;
We don't need margin top here. Flex in .small-error__contener should be enough to position it properly

2021-12-04 10:47 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +        min-width: 0;
Why min-width 0?

2021-12-04 11:17 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +                font-size: 0.6rem;
Font size should be based on size prop. Should be a bit smaller than icon size

2021-12-04 11:24 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +                <slot></slot>
I think we should use "text" prop instead of slot because this component is for text errors.

2021-12-04 11:24 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +<div class="small-error">
This component should be displayed only if it has some text to display

2021-12-04 11:26 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +      hover: false
I think that you could do display on hover with CSS only. Search the internet for solution.

2021-12-04 11:27 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +                background-color: #E13E3E;
You should use color variables from common.less

2021-12-05 01:25 UTC, kpagacz commented on frontend/src/App.vue
> +      <wof-small-error size=1>An element with position: fixed; is positioned relative to the viewport, which means it always stays in the same place even if the page is scrolled. The top, right, bott
That line needs breaks.

2021-12-05 01:26 UTC, kpagacz commented on frontend/src/App.vue
> +      <wof-small-error size=1>An element with position: fixed; is positioned relative to the viewport, which means it always stays in the same place even if the page is scrolled. The top, right, bott
Is there a reason there are none?

2021-12-05 01:27 UTC, kpagacz commented on frontend/src/components/WofSmallError.vue
> +            margin: 0.5em;
margin-right and margin defined at the same time? Is there a reason you didn't merge that property?

2021-12-05 01:29 UTC, kpagacz commented on frontend/src/App.vue
> +      <wof-small-error size=1>An element with position: fixed; is positioned relative to the viewport, which means it always stays in the same place even if the page is scrolled. The top, right, bott
Oh, I gues it's for testing only. Then you probably should stick this code in a comment on not include it in the PR

2021-12-05 01:31 UTC, kpagacz requested changes
I don't that component does what you wanted it too (considering your comment in App.vue). See how it looks on my screen:
![image](https://user-images.githubusercontent.com/24480246/144729877-425dadf9-699c-4e49-9507-90731cd6c642.png)

or am I missing the point?

2021-12-07 17:57 UTC, kpagacz commented
How is this going, @robert10290 ? Do you need some help with this?

2021-12-12 09:05 UTC, kpagacz commented
Also, can I ask you to bother writing some documentation - please, if you do, use this https://react-styleguidist.js.org/docs/getting-started/

2021-12-15 15:33 UTC, robert10290 commented
WofSmallError component is ready to check

2021-12-15 21:31 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +            <div class="small-error__content" :style="`font-size: ${size*0.6}rem;`">
Change it to size*0.5

2021-12-15 21:32 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +                padding: 0.5em;
Change it to 0.35em

2021-12-15 21:32 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +                    visibility: visible;
Change it to display: flex;

2021-12-15 21:33 UTC, karolkozlo commented on frontend/src/components/WofSmallError.vue
> +                visibility: hidden;
Instead of hiding visibility, set display: none;

2021-12-18 18:10 UTC, robert10290 commented
Ready to check.

2021-12-18 19:15 UTC, karolkozlo approved these changes
Maybe add some documentation later.

2021-12-22 02:04 UTC, kpagacz commented on frontend/src/components/WofSmallError.vue
> +            align-content: left;
This property still has an invalid value. https://developer.mozilla.org/en-US/docs/Web/CSS/align-content

2021-12-22 13:15 UTC, karolkozlo commented on frontend/src/components/WofInput.vue
> +      <div class="temporary-error" v-if="error.length && !isFocused"><wof-small-error :text="error" :size="1" /></div>
We don't need this div here. It was only temporary.
WofSmallError don't need to wrapped by this div.
Use this v-if directly on wof-small-error.
Set size to 1.5

2021-12-23 11:27 UTC, robert10290 commented
Ready to review. I will write documentation in another task for sure.

2021-12-30 22:08 UTC, kpagacz approved these changes

2021-12-30 22:54 UTC, merged