27 article list
kpagacz/wiki-on-fire pull request #183
Opened 2021-12-29 15:23 UTC by karolkozlo

closes #27

2021-12-29 15:23 UTC, karolkozlo commented
I tested it with this code in App.vue

```
<template>
  <main>
    <wof-header/>
    <div class="main-wrapper">
      <router-view msg="This is a basic frontend">
          <wof-article-list :articles="articles" :isButtonVisible="true" @add="addArticle"></wof-article-list>
      </router-view>
    </div>
    <wof-footer/>
  </main>
</template>

<script>
import WofFooter from './components/WofFooter.vue';
import WofHeader from './components/WofHeader.vue';
import WofArticleList from './components/WofArticleList.vue';

export default {
  components: { WofFooter, WofHeader, WofArticleList },
  name: "App",
  data() {
    return {
      articles: [
        {
          id: 1,
          title: 'Some interesting article1',
          linkToContents: 'https://en.wikipedia.org/wiki/Potato',
          dateAdded: '24.12.2021',
          lastModification: '27.12.2021',
          numberOfViews: 3401,
          numberOfEditions: 7
        },
        {
          id: 2,
          title: 'Best City at Mediterranean Sea Ever!!!!1!',
          linkToContents: 'https://en.wikipedia.org/wiki/Constantinople',
          dateAdded: '25.12.2021',
          lastModification: '28.12.2021',
          numberOfViews: 6543,
          numberOfEditions: 10
        },
        {
          id: 3,
          title: 'I know it from college',
          linkToContents: 'https://en.wikipedia.org/wiki/Turing_machine',
          dateAdded: '27.12.2021',
          lastModification: '22.12.2021',
          numberOfViews: 245,
          numberOfEditions: 1
        },
      ]
    }
  },
  methods: {
    addArticle(articleID) {
      console.log(articleID);
    }
  }
};
</script>

2021-12-30 23:17 UTC, kpagacz commented on frontend/src/components/WofArticleList.vue
> +                    Number of editions (this month)
Can we shorten this to just: views (last week) and edits (last month)?

2021-12-30 23:20 UTC, kpagacz requested changes
Some styling comments mainly. It does what it says on the tin!
![image](https://user-images.githubusercontent.com/24480246/147793983-bcb551ec-3f6e-41dd-91c4-97306358c15c.png)

2021-12-30 23:20 UTC, kpagacz commented on frontend/src/components/WofArticleList.vue
> +<template>
This file looks completely unformatted. I have run vetur on this and got a bunch of changesi in indentation, and spaces between if/for and brackets. Can you make sure a formatter is run on this?

2021-12-30 23:46 UTC, robert10290 commented on frontend/src/components/WofArticleList.vue
> +                for(let i=0; i<list.lenght; i++) {
typo here

2022-01-01 09:36 UTC, kpagacz approved these changes
LGTM

2022-01-01 10:19 UTC, merged