add(sequelize): initialized sequelize project
kpagacz/wiki-on-fire pull request #55
Opened 2021-11-04 19:34 UTC by kpagacz

* bootstrapped sequelize project
* created the first model - User
* created the first migration for User
* added a bunch of packages needed to support ES6 with node and sequelize
Closes #51 Closes #53

2021-11-04 19:38 UTC, kpagacz commented
You might want to test this one out (especially migrations) in tow with this: https://github.com/kpagacz/wiki-on-fire/pull/56

2021-11-10 19:01 UTC, mwiech99 requested changes
1. it's missing sequelize-cli dev dependents

2021-11-11 16:30 UTC, kpagacz commented
@mwiech99 , I updated the dependencies, model and the migration. Tested out on the docker mysql. Ready to review.

2021-11-15 18:35 UTC, mwiech99 approved these changes

2021-11-15 18:35 UTC, merged